[mgr]
ratio = [ 1, 3, 4 ]
linemode = "none"

[preview]
cache_dir = "/home/neo/.cache/yazi/"
image_filter = "nearest"
max_width = 2000
max_height = 2000
image_quality = 50

[tasks]
image_alloc = 0 
image_bound = [ 0, 0 ]
